name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Add GoReleaser APT repository
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update

      - name: Install GoReleaser
        run: sudo apt install -y goreleaser

      - name: Build and release
        run: goreleaser --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
